### PR TITLE
Fix storage slot read in bin/osm_price.sh

### PR DESCRIPTION
**Pull request by talbaneth**

### CODE REVIEW

**Review by iamchrissmith — COMMENTED** [review]
Double checking that I am understanding the change correctly.  The previous code worked but was actually reading the `nxt` value not the `curr` value.  Is that correct?

**Comment by talbaneth** [comment]
> Double checking that I am understanding the change correctly. The previous code worked but was actually reading the `nxt` value not the `curr` value. Is that correct?

Yeah, I couldn't figure out why after running drop_prices.sh the osm price seemed to not move, till I found this.
If you just use osm_price.sh to read the price before dropping it then most chances the next price will be good enough, and I assume this is why it didn't bother us so far.
We should fix it anyway.

**Review by iamchrissmith — APPROVED** [review]
lgtm

**Comment by godsflaw** [comment]
Oh awesome, I ran into this problem and didn't get a chance to dig in yet.  This explains what I was seeing.

**Review by godsflaw — APPROVED** [review]

**Pull request merged**
